name: Build

on:
  push:
  pull_request:
    branches:
    - main
    - release-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write
      packages: write
      id-token: write  # enable GitHub OIDC token issuance for this job

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Determine Version
        id: version
        uses: CenterEdge/actions/dotnet/nuget-version@v1
        with:
          tag-prefix: "release/"

      - uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Build
        working-directory: ./src
        run: dotnet build --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version  }}
      - name: Test
        working-directory: ./src
        run: dotnet test --no-build --configuration Release -- --report-github
      - name: Pack
        working-directory: ./src
        run: dotnet pack --no-build --configuration Release -p:Version=${{ steps.version.outputs.version }}

      - name: NuGet login
        uses: NuGet/login@v1
        if: ${{ steps.version.outputs.is-release == 'true' }}
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Push to NuGet.org
        if: ${{ steps.version.outputs.is-release == 'true' }}
        working-directory: ./src/artifacts/package
        run: |
          dotnet nuget push **/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Push to GitHub Packages
        if: ${{ startsWith(github.ref, 'refs/pull/') || steps.version.outputs.is-release == 'true' }}
        working-directory: ./src/artifacts/package
        run: |
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/CenterEdge/index.json --skip-duplicate
